# This is a basic workflow to help you get started with Actions

name: build-node-ci

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node.version}}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-ejemplo
          path: dist/
          retention-days: 14
  deploy:
    name: dummy deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://www.google.com
    steps:
      - name: imprimir variables entorno
        run: echo "Secret var ${{secrets.secret1}}"
